# Rhass
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

/**
 *
 * @author samsung
 */
public class Visitante extends Pessoa {
   
    
    
    public String getComentar() {
        return Comentar;
    }

    public void setComentar(String Comentar) {
        this.Comentar = Comentar;
    }
      private String Comentar;
    
    
}
